blog_django/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'
urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('register/', user_register, name='user_register'),
    path('logout/',user_logout, name='user_logout')
]

blog_django/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', all_articles, name='all_articles'),
    path('<int:id>/<slug:slug>/', get_article, name='get_article')

]

blog_django/blog_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls', namespace="blog")),
                  path('accounts/', include('accounts.urls', namespace="accounts")),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_django/accounts/models.py
from django.db import models

# Create your models here.

blog_django/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class PublishedArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='created')


class Article(models.Model):
    STATUS = (
        ("draft", "Draft"),
        ("created", "Created"),
    )
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, unique=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    body = RichTextUploadingField(null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS, default="draft")
    objects = models.Manager()
    published = PublishedArticleManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:get_article', args=[self.id, self.slug])

blog_django/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField(label='Email', max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'enter your username'}))
    password = forms.CharField(max_length=40,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Enter your password'}))


class UserRegistrationForm(forms.Form):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'your username'}))

    email = forms.EmailField(max_length=50,
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'your email'}))

    password1 = forms.CharField(label='Password', max_length=40,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'your password'}))

    password2 = forms.CharField(label='confirm password', max_length=40,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'enter your password again'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        data = User.objects.filter(email=email)
        if data.exists():
            raise forms.ValidationError("this email is already exists")
        return email

    # def clean_password2(self):
    #     p1 = self.cleaned_data['password1']
    #     p2 = self.cleaned_data['password2']
    #
    #     if p1 != p2:
    #         raise forms.ValidationError('passwords must be equal')
    #     return p1

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 and p2:
            if p1 != p2:
                raise forms.ValidationError('passwords must be match')

blog_django/accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "logged in successfully", "success")
                return redirect('blog:all_articles')
            else:
                messages.error(request, "your username or password is incorrect", "danger")
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(request, 'your account have been created successfully', 'success')
            return redirect('accounts:user_login')

    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'you are successfully logged out', 'success')
    return redirect('blog:all_articles')

blog_django/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article


def all_articles(request):
    articles = Article.published.all()
    return render(request, "blog/all_articles.html", {"articles": articles})


def get_article(request, id, slug):
    # article = Article.objects.get(id=id, slug=slug)
    article = get_object_or_404(Article, id=id, slug=slug)
    return render(request, "blog/article.html", {"article": article})

blog_django/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login" />
    </form>
{% endblock %}

blog_django/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register" class="btn btn-primary"/>
    </form>
{% endblock %}

blog_django/blog/templates/blog/all_articles.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
    {% for article in articles %}
        <a href="{{ article.get_absolute_url}}"class="card-body">{{ article }}</a>
    {% endfor %}
    </div>
{% endblock %}

blog_django/blog/templates/blog/article.html
{% extends 'base.html' %}
{% load static %}
{% block customization %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}
{% block content %}
    <h3>{{ article.title }}</h3>
    <small>{{ article.created|date:'F.j.Y.P' }}</small>
    <br>
    <small>{{ article.writer.username }}</small>
        <hr>
    <p>{{ article.body|safe }}</p>
{% endblock %}

blog_django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% block customization %}{% endblock %}
</head>
<body>

    {% include "./inc/navbar.html" %}
    <div class="jumbotron">
        {% include './inc/messages.html' %}
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

blog_django/templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

blog_django/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'blog:all_articles' %}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
        {% else %}
            <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
        {% endif %}

  </div>
</nav>